development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  database: db/test.sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8  # cloud sql uses utf8, assuming your local instance is reconfigured properly, it should be too
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: dnata
  password: rememberme
  database: monolith_db
  port: <%= ENV.fetch("DB_PORT") { 5432 }%>
  # host: <%= ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' } %>/<%= ENV["CLOUD_SQL_CONNECTION_NAME"] %>  
  # host: <%= ENV.fetch("INSTANCE_HOST") { "localhost" } %>
  host: /var/run/postgresql